In [4]:
import pandas as pd

In [5]:
# s = pd.Series([1, 2, 3, 5, 7])
# s

0    1
1    2
2    3
3    5
4    7
dtype: int64

In [6]:
# print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [15]:
# print(s.values)

In [18]:
s = pd.Series([9904312, 3448737, 2890451, 2466052])
index=['서울', '부산', '인천', '대구']
print(s)

0    9904312
1    3448737
2    2890451
3    2466052
dtype: int64


In [21]:
print(s.index)

RangeIndex(start=0, stop=4, step=1, name='도시')


In [20]:
print(s.values)

[9904312 3448737 2890451 2466052]


In [19]:
s.name = "인구"
s.index.name = "도시"
print(s)

도시
0    9904312
1    3448737
2    2890451
3    2466052
Name: 인구, dtype: int64


In [ ]:
print(pd.Series(range(1, 5)))

In [6]:
s = pd.Series(['samsung', 81000])
print(s)                      #81000 은 정수형으로 바꾼 후 계산이 필요하다.

0    samsung
1      81000
dtype: object


In [9]:
from pandas import Series

data = [1000, 2000, 3000]
s = Series(data)
print(s.index)
print(s.index.to_list())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [10]:
data =[1000, 2000, 3000]
s = Series(data)
s.index = ['메로나', '구구콘', '하겐다즈']
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [14]:
data =[1000, 2000, 3000]
index = ['메로나', '구구콘', '하겐다즈']
s = Series(data=data, index=index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [15]:
s2 = s.reindex(["메로나", "비비빅", "구구콘"])
print(s2)

메로나    1000.0
비비빅       NaN
구구콘    2000.0
dtype: float64


In [17]:
s2 = s2.fillna(0)
print(s2)

메로나    1000.0
비비빅       0.0
구구콘    2000.0
dtype: float64


In [18]:
price = [42500, 42550, 41800, 42550, 42650]
date = ["2019-05-31", "2019-05-30", "2019-05-29", "2019-05-28", "2019-05-27"]
s = Series(price, date)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [19]:
data = {
    "2019-05-31" : 42500,
    "2019-05-30" : 42550,
    "2019-05-29" : 41800,
    "2019-05-28" : 42550,
    "2019-05-27" : 42650
}
s = Series(data)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [20]:
print(s.index)

Index(['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27'], dtype='str')


In [21]:
print(s.index.dtype)

str


In [22]:
print(s.values)

[42500 42550 41800 42550 42650]


In [23]:
s1 = Series([10, 20, 30])
s2 = Series([10, 20, 30], index= [1, 2, 3])
print(s1[0])
print(s2[1])


10
10


In [27]:
s3 = Series([10, 20, 30], index = ['a', 'b', 'c'])
print(s3['a'])

10


In [28]:
print(s3.index[0])
print(s3.index[-1])

a
c


In [29]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=['서울', '부산', '인천', '대구'])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [30]:
print(s[1:3])

부산    3448737
인천    2890451
dtype: int64


In [31]:
print(s['부산':'대구'])
#행 인덱스는 대구까지 포함

부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [34]:
print(s[1:])

부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [35]:
s1 = pd.Series(range(3), index = ['a', 'b', 'c'])
s1

a    0
b    1
c    2
dtype: int64

In [36]:
print(s1.a)
print(s1["a"])

0
0


In [41]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], 
            index=['서울', '부산', '인천', '대구'])
s


서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [42]:
print("대구" in s)

True


In [43]:
print("대전" in s)

False


In [44]:
for key, value in s.items():
    print("%s : %d" % (key, value))

서울 : 9904312
부산 : 3448737
인천 : 2890451
대구 : 2466052


In [45]:
s2 = pd.Series({'서울': 9631482, '부산': 3393191, '인천' : 2632035, '대전':1490158})
print(s2)

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64


In [46]:
s2 = pd.Series({'서울': 9631482, '부산': 3393191, '인천' : 2632035, '대전':1490158},
                index=['부산', '서울', '인천', '대전'])
print(s2)

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64


In [47]:
from pandas import Series

data = [1000, 2000, 3000]
index = ["메로나", "구구콘", "라겐다즈"]
s = Series(data, index)
s

메로나     1000
구구콘     2000
라겐다즈    3000
dtype: int64

In [48]:
print(s.iloc[0:2])

메로나    1000
구구콘    2000
dtype: int64


In [49]:
print(s.loc['메로나':'구구콘'])

메로나    1000
구구콘    2000
dtype: int64


In [50]:
indice = [0,2] #리스트로 나열해서 추출
print(s.iloc[ indice ])

메로나     1000
라겐다즈    3000
dtype: int64


In [51]:
print(s.iloc[ [0,2] ] ) #리스트를 뭐? 50번째 사용한 것도 같은 의미이다.

메로나     1000
라겐다즈    3000
dtype: int64


In [53]:
indice = ['메로나', '라겐다즈']
print(s.loc[ indice ])
print(s.loc[ ['메로나', '라겐다즈'] ])

메로나     1000
라겐다즈    3000
dtype: int64
메로나     1000
라겐다즈    3000
dtype: int64


In [54]:
s.loc['메로나'] = 500   # s.iloc[0] = 500, s['메로나'] = 500
print(s)

메로나      500
구구콘     2000
라겐다즈    3000
dtype: int64


In [55]:
s.loc['비비빅'] = 500
print(s)

메로나      500
구구콘     2000
라겐다즈    3000
비비빅      500
dtype: int64


In [57]:
s = s.drop('메로나') #시리즈 구조에 변화가 있는 것이라 저장을 해야 됨
print(s)

KeyError: "['메로나'] not found in axis"

In [58]:
s

구구콘     2000
라겐다즈    3000
비비빅      500
dtype: int64

In [62]:
s = pd.Series([ 9631482, 3393191, 2632035, 490158],
             index = [ '서울','부산','인천', '대구'])
s2 = pd.Series({'서울': 9631482, '부산': 3393191, '인천' : 2632035, '대전':1490158},
               index = ['부산','서울','인천','대전'])

ds = s -s2
print(ds)    

대구    NaN
대전    NaN
부산    0.0
서울    0.0
인천    0.0
dtype: float64


In [63]:
s3 = s / 100000
print(s3)

서울    96.31482
부산    33.93191
인천    26.32035
대구     4.90158
dtype: float64


In [64]:
print(s.values - s2.values)

[ 6238291 -6238291        0 -1000000]


In [65]:
print(ds[ds.notnull()])

부산    0.0
서울    0.0
인천    0.0
dtype: float64


In [66]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [67]:
rs = (s - s2) / s2 * 100
print(rs)

대구    NaN
대전    NaN
부산    0.0
서울    0.0
인천    0.0
dtype: float64


In [68]:
rs = rs[rs.notnull()]
print(rs)

부산    0.0
서울    0.0
인천    0.0
dtype: float64


In [69]:
rs['부산'] = 1.63
rs['대구'] = 1.41
print(rs)

부산    1.63
서울    0.00
인천    0.00
대구    1.41
dtype: float64


In [74]:
del rs['서울']
print(rs)

KeyError: '서울'

In [73]:
from pandas import Series

date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = Series([42800, 42700, 42050, 42950, 43000], index = date)
low = Series([42150, 42150, 41300, 42150, 42350], index = date)
print(high)
print('----------------------------')
print(low)

6/1    42800
6/2    42700
6/3    42050
6/4    42950
6/5    43000
dtype: int64
----------------------------
6/1    42150
6/2    42150
6/3    41300
6/4    42150
6/5    42350
dtype: int64


In [77]:
diff = high - low

In [78]:
print(diff.max())

800


In [79]:
print(diff.idxmax())

6/4


In [84]:
data = {
    "삼성전자" : "전기,전자",
    "LG전자" : "전기,전자",
    "현대차" : "운수장비",
    "NAVER" : "서비스업",
    "카카오" : "서비스업"
}
s = Series(data)
print(s)

삼성전자     전기,전자
LG전자     전기,전자
현대차       운수장비
NAVER     서비스업
카카오       서비스업
dtype: str


In [85]:
print(s.unique())

<StringArray>
['전기,전자', '운수장비', '서비스업']
Length: 3, dtype: str


In [86]:
print(s.value_counts())

전기,전자    2
서비스업     2
운수장비     1
Name: count, dtype: int64


In [87]:
import pandas as pd
import numpy as np   #행렬 연산에 강함 

s = pd.Series(['선화', '강호', np.nan, '소정', '우영']) #nan 데이터를 나타낸다.
print(s)

0     선화
1     강호
2    NaN
3     소정
4     우영
dtype: str


In [89]:
s.isnull()
s.isna()    #동일한 기능 수행함.

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [90]:
s[s.isnull()]

2    NaN
dtype: str

In [91]:
s[s.notnull()]

0    선화
1    강호
3    소정
4    우영
dtype: str

In [99]:
def remouve_comma(x):
    print(x, 'in function')
    return x

In [104]:
s = Series(['1,234', '5,678','9,876'])
result = list(s.map(remouve_comma))  #map함수는 반복자 객체가 앞에 있다. 데이터 개수만큼 반복한다. 3개 있으니 3번 반복 호출한다.
print(result)

1,234 in function
5,678 in function
9,876 in function
['1,234', '5,678', '9,876']


In [105]:
def remove_comma(x) :
    return int(x.replace(",", ""))

In [106]:
s = Series(['1,234', '5,678','9,876'])
result = list(s.map(remouve_comma)) 
print(result)             #""없애기 근데 출력이 안됨 다ㅣㅅ 확인

1,234 in function
5,678 in function
9,876 in function
['1,234', '5,678', '9,876']


In [108]:
from pandas import Series
data = [42500, 42550, 41800, 42550, 42650]
index = ["2019-05-31", "2019-05-30", "2019-05-29", "2019-05-28", "2019-05-27"]
s = Series(data=data, index=index)
print(s)


2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [109]:
cond = s > 42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [110]:
print(s[s > 42000])

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [116]:
from pandas import Series

data = [3.1, 2.0, 10.1, 5.1]
index = ['000010', '000020', '000030', '000040']
s = Series(data=data, index=index)
print(s)

000010     3.1
000020     2.0
000030    10.1
000040     5.1
dtype: float64


In [117]:
s1 = s.sort_values()
print(s1)

000020     2.0
000010     3.1
000040     5.1
000030    10.1
dtype: float64


In [118]:
s1 = s.sort_values(ascending=False)
print(s1)

000030    10.1
000040     5.1
000010     3.1
000020     2.0
dtype: float64


In [119]:
s2 = s.rank()
print(s2)

000010    2.0
000020    1.0
000030    4.0
000040    3.0
dtype: float64


In [120]:
s2 = s.rank(ascending=False)
print(s2)

000010    3.0
000020    4.0
000030    1.0
000040    2.0
dtype: float64
